/**
 * Audio Commands — Music Gen, TTS, Transcribe
 */

export class MusicCommand {
  constructor(ai, conversations, embedBuilder) {
    this.ai = ai;
    this.embed = embedBuilder;
  }

  async execute(interaction) {
    const prompt = interaction.data.options?.[0]?.value;
    const duration = interaction.data.options?.[1]?.value || 10;
    const userName = interaction.member?.user?.global_name || interaction.member?.user?.username || "User";

    const result = await this.ai.generateMusic(prompt, interaction.member?.user?.id, { duration });

    if (!result.success) {
      return ({
        type: 4,
        data: { embeds: [this.embed.error("🎵 Music Generation Failed", result.error)] },
      });
    }

    return ({
      type: 4,
      data: {
        embeds: [{
          title: "🎵 AI Generated Music",
          description: `**Prompt:** ${prompt}\n**Duration:** ${result.duration}s\n**Model:** ${result.model}\n**Provider:** ${result.provider}`,
          color: 0x9b59b6,
          footer: { text: `Generated by ${userName} • MusicGen` },
        }],
      },
    });
  }
}

export class TTSCommand {
  constructor(ai, conversations, embedBuilder) {
    this.ai = ai;
    this.embed = embedBuilder;
  }

  async execute(interaction) {
    const text = interaction.data.options?.[0]?.value;
    const voice = interaction.data.options?.[1]?.value || "id-ID-ArdiNeural";
    const userName = interaction.member?.user?.global_name || interaction.member?.user?.username || "User";

    const result = await this.ai.textToSpeech(text, interaction.member?.user?.id, { voice });

    if (!result.success) {
      return ({
        type: 4,
        data: { embeds: [this.embed.error("🗣️ TTS Failed", result.error)] },
      });
    }

    return ({
      type: 4,
      data: {
        embeds: [{
          title: "🗣️ Text-to-Speech",
          description: `**Text:** ${text.substring(0, 500)}\n**Voice:** ${voice}\n**Model:** ${result.model}`,
          color: 0x2ecc71,
          footer: { text: `Generated by ${userName} • TTS` },
        }],
      },
    });
  }
}

export class TranscribeCommand {
  constructor(ai, conversations, embedBuilder) {
    this.ai = ai;
    this.embed = embedBuilder;
  }

  async execute(interaction) {
    const audioUrl = interaction.data.options?.[0]?.value;
    const userName = interaction.member?.user?.global_name || interaction.member?.user?.username || "User";

    const transcript = await this.ai.transcribeAudio(audioUrl, interaction.member?.user?.id);

    return ({
      type: 4,
      data: {
        embeds: [{
          title: "📝 Transcription",
          description: transcript,
          color: 0x3498db,
          footer: { text: `Transcribed by ${userName} • Whisper` },
        }],
      },
    });
  }
}