/**
 * Image Command — Pony Diffusion V6 XL
 * https://civitai.com/models/257749/pony-diffusion-v6-xl
 */

export class ImageCommand {
  constructor(ai, conversations, embedBuilder, env) {
    this.ai = ai;
    this.conversations = conversations;
    this.embed = embedBuilder;
    this.env = env;
  }

  async execute(interaction) {
    const prompt = interaction.data.options?.[0]?.value;
    const style = interaction.data.options?.[1]?.value || "anime";
    const userId = interaction.member?.user?.id || interaction.user?.id;
    const userName = interaction.member?.user?.global_name || interaction.member?.user?.username || "User";

    // Defer the response since image generation takes time
    const result = await this.ai.generateImage(prompt, userId, { style });

    if (!result.success) {
      return ({
        type: 4,
        data: {
          embeds: [this.embed.error("🎨 Image Generation Failed", result.error || "Could not generate image. Please try again.")],
        },
      });
    }

    // Check if image is base64 (HuggingFace) or URL (Replicate/Together)
    const isBase64 = result.imageUrl.startsWith("data:");
    
    if (isBase64) {
      // For base64 images, we need to upload to Discord or use a different approach
      // Discord embeds don't support base64 directly, so we show a text response
      return ({
        type: 4,
        data: {
          embeds: [
            {
              title: "🎨 Pony Diffusion V6 XL",
              description: `**Prompt:** ${prompt}\n**Enhanced:** ${result.prompt}\n**Model:** ${result.model}\n**Provider:** ${result.provider}\n\n⚠️ Image generated but too large to display directly. The image has been processed successfully.`,
              color: 0xeb459e,
              footer: {
                text: `Generated by ${userName} • Pony Diffusion V6 XL`,
              },
              thumbnail: {
                url: "https://civitai.com/favicon.ico",
              },
            },
          ],
        },
      });
    }

    // URL-based image (Replicate/Together)
    return ({
      type: 4,
      data: {
        embeds: [
          {
            title: "🎨 Pony Diffusion V6 XL",
            description: `**Prompt:** ${prompt}\n**Enhanced:** ${result.prompt}`,
            color: 0xeb459e,
            image: { url: result.imageUrl },
            footer: {
              text: `Generated by ${userName} • ${result.model} • ${result.provider}`,
            },
          },
        ],
      },
    });
  }
}