/**
 * Vision Commands — Analyze, OCR, Video
 */

export class AnalyzeCommand {
  constructor(ai, conversations, embedBuilder) {
    this.ai = ai;
    this.embed = embedBuilder;
  }

  async execute(interaction) {
    const imageUrl = interaction.data.options?.[0]?.value;
    const question = interaction.data.options?.[1]?.value || "Describe this image in detail.";
    const userName = interaction.member?.user?.global_name || interaction.member?.user?.username || "User";

    const analysis = await this.ai.analyzeImage(imageUrl, question, interaction.member?.user?.id);

    return ({
      type: 4,
      data: {
        embeds: [{
          title: "👁️ Image Analysis",
          description: `**Question:** ${question}\n\n${analysis}`,
          color: 0xe67e22,
          thumbnail: { url: imageUrl },
          footer: { text: `Analyzed by ${userName} • LLaVA Vision` },
        }],
      },
    });
  }
}

export class OCRCommand {
  constructor(ai, conversations, embedBuilder) {
    this.ai = ai;
    this.embed = embedBuilder;
  }

  async execute(interaction) {
    const imageUrl = interaction.data.options?.[0]?.value;
    const userName = interaction.member?.user?.global_name || interaction.member?.user?.username || "User";

    const text = await this.ai.ocrImage(imageUrl);

    return ({
      type: 4,
      data: {
        embeds: [{
          title: "📄 OCR — Text Extracted",
          description: text.substring(0, 1900),
          color: 0x1abc9c,
          thumbnail: { url: imageUrl },
          footer: { text: `Extracted by ${userName} • TrOCR` },
        }],
      },
    });
  }
}

export class VideoCommand {
  constructor(ai, conversations, embedBuilder) {
    this.ai = ai;
    this.embed = embedBuilder;
  }

  async execute(interaction) {
    const prompt = interaction.data.options?.[0]?.value;
    const userName = interaction.member?.user?.global_name || interaction.member?.user?.username || "User";

    const result = await this.ai.generateVideo(prompt, interaction.member?.user?.id);

    if (!result.success) {
      return ({
        type: 4,
        data: { embeds: [this.embed.error("🎬 Video Generation Failed", result.error)] },
      });
    }

    return ({
      type: 4,
      data: {
        embeds: [{
          title: "🎬 AI Generated Video",
          description: `**Prompt:** ${prompt}\n**Model:** ${result.model}\n**Provider:** ${result.provider}`,
          color: 0xe91e63,
          video: result.videoUrl ? { url: result.videoUrl } : undefined,
          footer: { text: `Generated by ${userName} • SVD` },
        }],
      },
    });
  }
}